namespace Neo.RPC
{
    public enum ApiMethods
    {
        getaccountstate,
        getassetstate,
        //getbalance,
        getbestblockhash,
        getblock,
        getblockcount,
        getblocksysfee,
        getblockhash,
        getconnectioncount,
        getcontractstate,
        getrawmempool,
        getrawtransaction,
        getstorage,
        gettxout,
        getversion,
        invoke,
        invokefunction,
        sendrawtransaction,
        sendtoaddress,
        sendmany,
        //getnewaddress,
        //dumpprivkey,
        validateaddress,
        getpeers,
    }
}
